"""Tests for the Korean health-screening cohort pipeline (T7) on the SYNTHETIC fixture.

The fixture (tests/fixtures/korea_cohort/screening_exams_fixture.csv) is
generated by tests/fixtures/korea_cohort/make_fixture.py.  No number derived
from it may be reported anywhere, and nothing here writes into results/.
"""
from __future__ import annotations

import filecmp
import json
import os
import subprocess
import sys

import numpy as np
import pandas as pd
import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

SCRIPTS = os.path.join(ROOT, "scripts", "korea_cohort")
PREPARE = os.path.join(SCRIPTS, "prepare_korea_cohort.py")
ANALYZE = os.path.join(SCRIPTS, "analyze_korea_cohort.py")
FIXTURE_DIR = os.path.join(ROOT, "tests", "fixtures", "korea_cohort")
FIXTURE = os.path.join(FIXTURE_DIR, "screening_exams_fixture.csv")
MAKE_FIXTURE = os.path.join(FIXTURE_DIR, "make_fixture.py")
RESULTS = os.path.join(ROOT, "results")
MIN_CELL = 10


def run(*args, timeout=900):
    return subprocess.run([sys.executable, *args], capture_output=True, text=True, timeout=timeout, cwd=ROOT)


def results_snapshot():
    if not os.path.isdir(RESULTS):
        return {}
    return {f: os.path.getmtime(os.path.join(RESULTS, f)) for f in os.listdir(RESULTS)}


def walk_cells(o, path="$"):
    """Yield every published count / rate dict (has a 'suppressed' key)."""
    if isinstance(o, dict):
        if "suppressed" in o and ("n" in o or "value" in o):
            yield path, o
        for k, v in o.items():
            yield from walk_cells(v, f"{path}.{k}")
    elif isinstance(o, list):
        for i, v in enumerate(o):
            yield from walk_cells(v, f"{path}[{i}]")


def assert_suppression_rule(o):
    for path, c in walk_cells(o):
        if c["suppressed"]:
            assert c.get("n") is None and c.get("value") is None, path
        else:
            n = c["n"]
            assert n is not None and (n == 0 or n >= MIN_CELL), f"{path}: small cell published: {c}"


def sidecar_of(prepared):
    return os.path.splitext(str(prepared))[0] + ".json"


# ------------------------------------------------------------ fixtures
@pytest.fixture(scope="module")
def prepared(tmp_path_factory):
    out = tmp_path_factory.mktemp("kc_prep") / "prepared.parquet"
    r = run(PREPARE, "--fixture", FIXTURE, "--out", str(out))
    assert r.returncode == 0, r.stderr + r.stdout
    path = out if out.exists() else out.with_suffix(".csv")     # CSV fallback without pyarrow
    assert path.exists() and os.path.exists(sidecar_of(path))
    return path


@pytest.fixture(scope="module")
def us_bounds(tmp_path_factory):
    """A small US-bounds JSON with per-unit nuisances (synthetic, tests only)."""
    rng = np.random.default_rng(7)
    n = 120
    scores = rng.normal(size=n)
    p1 = np.clip(1 / (1 + np.exp(-(-0.7 + 0.9 * scores + rng.normal(0, 0.4, n)))), 0.02, 0.98)
    e = rng.uniform(0.3, 0.9, n)
    d = {"data_source": "synthetic", "model": "test", "population": "test",
         "gamma": 1.885, "auroc_lo": 0.55, "auroc_hi": 0.75,
         "by_gamma": {"1": {"auroc_lo": 0.66, "auroc_hi": 0.66}, "1.885": {"auroc_lo": 0.55, "auroc_hi": 0.75}},
         "nuisances": {"scores": scores.tolist(), "p1": p1.tolist(), "e": e.tolist()}}
    path = tmp_path_factory.mktemp("kc_us") / "us_bounds.json"
    path.write_text(json.dumps(d))
    return path


@pytest.fixture(scope="module")
def analysis(prepared, us_bounds, tmp_path_factory):
    out = tmp_path_factory.mktemp("kc_an") / "analysis.json"
    before = results_snapshot()
    r = run(ANALYZE, "--prepared", str(prepared), "--us-bounds", str(us_bounds), "--fixture",
            "--nuisance-model", "logistic", "--n-boot", "30", "--seeds", "5",
            "--us-gamma-min", "1.5", "--us-odds-ratio", "1.885", "--out", str(out))
    assert r.returncode == 0, r.stderr + r.stdout
    assert results_snapshot() == before, "analysis on the fixture must not touch results/"
    with open(out) as f:
        return json.load(f)


# ------------------------------------------------------- (a) real path
def test_real_path_missing_data_root_exits_2(tmp_path):
    root = tmp_path / "no_such_root"
    out = tmp_path / "prepared.parquet"
    r = run(PREPARE, "--data-root", str(root), "--out", str(out))
    assert r.returncode == 2, r.stderr
    assert str(root / "screening_exams.csv") in r.stderr
    assert "simulator" in r.stderr.lower()
    assert not out.exists() and not (tmp_path / "prepared.csv").exists()
    assert not (tmp_path / "prepared.json").exists()


def test_missing_fixture_file_exits_2(tmp_path):
    r = run(PREPARE, "--fixture", str(tmp_path / "nope.csv"), "--out", str(tmp_path / "p.parquet"))
    assert r.returncode == 2
    assert "nope.csv" in r.stderr


def test_default_data_root_is_absent_here(tmp_path):
    """Without --data-root the real default is used; in this environment it is absent."""
    if os.path.exists("/data/korea_screening/screening_exams.csv"):
        pytest.skip("real data present")
    r = run(PREPARE, "--out", str(tmp_path / "p.parquet"))
    assert r.returncode == 2 and "/data/korea_screening/screening_exams.csv" in r.stderr


# ----------------------------------------------- (b) prepare on fixture
def test_fixture_is_reproducible(tmp_path):
    out = tmp_path / "regen.csv"
    r = run(MAKE_FIXTURE, "--out", str(out))
    assert r.returncode == 0, r.stderr
    assert "SYNTHETIC" in r.stdout
    assert filecmp.cmp(str(out), FIXTURE, shallow=False), "committed fixture differs from make_fixture.py output"


def test_prepare_fixture_sidecar_and_suppression(prepared):
    with open(sidecar_of(prepared)) as f:
        side = json.load(f)
    assert side["data_source"] == "synthetic"
    assert side["schema_version"] == "1.0"
    assert len(side["input"]["sha256"]) == 64
    c = side["counts"]
    assert c["n_raw"] == 400
    assert c["n_dropped_dedup"] == 35                     # designed same-year duplicates
    assert c["n_dropped_window"] > 0
    assert c["n_final"] == c["n_raw"] - c["n_dropped_dedup"] - c["n_dropped_window"]
    assert c["n_centres"] == 5
    # the 2021 cell holds five exams -> suppressed (null + flag)
    y2021 = side["per_year"]["2021"]
    assert y2021["suppressed"] is True and y2021["n"] is None
    assert any(v["suppressed"] for v in side["per_year"].values())
    assert_suppression_rule(side)
    assert side["cohort"]["outcome_observed_all"] is True   # truth-batch cohort
    assert side["cohort"]["T_all_one"] is False             # the follow-up decision varies
    assert set(side["Z_levels"]) == {"KC01", "KC02", "KC03", "KC04", "KC05"}


def test_prepared_file_contents(prepared):
    with open(sidecar_of(prepared)) as f:
        side = json.load(f)
    df = pd.read_parquet(prepared) if str(prepared).endswith(".parquet") else pd.read_csv(prepared)
    assert len(df) == side["counts"]["n_final"] == side["prepared"]["n_rows"]
    for col in ("subject_id", "exam_date", "exam_year", "centre_id", "Z", "T", "Y_full", "Y_obs",
                "public_model_score", "followup_days"):
        assert col in df.columns
    assert not df.duplicated(["subject_id", "exam_year"]).any()       # one exam per subject-year
    assert set(df["T"].unique()) == {0, 1}
    assert df["Y_full"].notna().all()
    assert df.loc[df["T"] == 0, "Y_obs"].isna().all() and df.loc[df["T"] == 1, "Y_obs"].notna().all()
    assert (df["Z"].map(dict(enumerate(side["Z_levels"]))) == df["centre_id"]).all()
    feats = side["prepared"]["features"]
    assert feats and all(f in df.columns for f in feats)
    x = df[[f for f in feats if f.startswith("x_")]].to_numpy(float)
    assert np.allclose(x.mean(0), 0, atol=1e-8) and np.allclose(x.std(0), 1, atol=1e-6)
    assert "m_bmi" in feats and set(df["m_bmi"].unique()) <= {0.0, 1.0}
    assert "bmi" not in df.columns                                     # only standardised covariates
    # the window rule: no unit without an event has < 365 days of follow-up
    assert ((df["Y_full"] == 1) | (df["followup_days"] >= 365)).all()


def test_prepare_schema_violation_exits_3(tmp_path):
    df = pd.read_csv(FIXTURE)
    df.loc[0, "sex"] = "X"
    df.loc[1, "bmi"] = 999.0
    df.loc[2, "exam_date"] = "2019/01/01"
    df.loc[3, "followup_test_ordered"] = 1
    df.loc[3, "outcome"] = np.nan
    bad = tmp_path / "bad.csv"
    df.to_csv(bad, index=False)
    r = run(PREPARE, "--fixture", str(bad), "--out", str(tmp_path / "p.parquet"))
    assert r.returncode == 3, r.stderr
    for token in ("sex", "bmi", "exam_date", "outcome must be recorded"):
        assert token in r.stderr
    assert not (tmp_path / "p.parquet").exists() and not (tmp_path / "p.json").exists()
    # a missing required column is a schema violation too
    df2 = pd.read_csv(FIXTURE).drop(columns=["centre_id"])
    bad2 = tmp_path / "bad2.csv"
    df2.to_csv(bad2, index=False)
    r2 = run(PREPARE, "--fixture", str(bad2), "--out", str(tmp_path / "p2.parquet"))
    assert r2.returncode == 3 and "centre_id" in r2.stderr


def test_prepare_refuses_results_dir_for_fixture():
    before = results_snapshot()
    target = os.path.join(RESULTS, "korea_cohort_TEST_SHOULD_NOT_EXIST.parquet")
    r = run(PREPARE, "--fixture", FIXTURE, "--out", target)
    assert r.returncode == 4
    assert not os.path.exists(target) and not os.path.exists(os.path.splitext(target)[0] + ".json")
    assert results_snapshot() == before


# ----------------------------------------------- (c) analyze on fixture
def test_analyze_fixture_top_level(analysis):
    for k in ("data_source", "n_seeds", "n_boot_per_seed", "inputs", "cohort", "containment",
              "gamma_comparison", "privacy", "software"):
        assert k in analysis
    assert analysis["data_source"] == "synthetic"
    assert analysis["n_seeds"] == 5 and analysis["rule4_compliant"] is True
    assert analysis["inputs"]["prepared"]["sidecar_data_source"] == "synthetic"
    assert analysis["privacy"]["min_cell"] == MIN_CELL
    assert_suppression_rule(analysis)


def test_analyze_containment(analysis):
    c = analysis["containment"]
    assert c["available"] is True
    assert c["batch_cohort_outcome_observed_all"] is True and c["T_all_one"] is False
    assert isinstance(c["contains_point"], bool)
    assert isinstance(c["contains_ci"], bool) and isinstance(c["overlaps_ci"], bool)
    ra = c["realised_auroc"]
    assert 0.0 < ra["point"] < 1.0
    lo, hi = ra["ci95"]
    assert lo <= ra["point"] <= hi
    assert ra["n_resamples"] == 5 * 30 and len(ra["per_seed"]) == 5
    assert ra["over_seeds"]["n"] == 5 and ra["over_seeds"]["ci95"] is not None
    assert c["us_bounds"]["gamma"] == 1.885 and c["us_bounds"]["auroc_lo"] == 0.55
    assert c["contains_point"] == (0.55 <= ra["point"] <= 0.75)
    mg = c["min_gamma_containing"]
    assert mg["method"] == "recomputed_from_nuisances" and mg["n_us_units"] == 120
    assert mg["gamma"] is None or (isinstance(mg["gamma"], float) and mg["gamma"] >= 1.0)


def test_analyze_gamma_comparison(analysis):
    g = analysis["gamma_comparison"]
    assert g["T_varies"] is True and g["outcome_recorded_for_T0"] is True
    assert g["us_gamma_min"] == 1.5 and g["us_odds_ratio"] == 1.885
    gm = g["gamma_min"]
    assert gm["available"] is True and gm["n_centres_used"] >= 2
    for key in ("gamma_min", "gamma_min_q95", "gamma_min_boot_lo"):
        s = gm[key]
        assert s["n"] == 5 and s["mean"] >= 1.0 and s["ci95"] is not None
    assert 0.0 <= gm["refutes_MAR_fraction"] <= 1.0
    assert set(gm["per_centre"]) == {"KC01", "KC02", "KC03", "KC04", "KC05"}
    orr = g["odds_ratio"]
    assert orr["available"] is True and orr["point"] > 0
    assert orr["ci95"][0] <= orr["point"] <= orr["ci95"][1]
    assert orr["gamma_scale_magnitude"] >= 1.0
    assert isinstance(g["gamma_min_vs_us"]["korea_ci95_contains_us"], bool)
    v = g["odds_ratio_vs_us"]
    assert isinstance(v["korea_ci95_contains_us"], bool) and isinstance(v["same_direction"], bool)
    assert v["us_odds_ratio"] == 1.885


def test_analyze_output_is_aggregate_only(analysis):
    def walk(o, path="$"):
        if isinstance(o, dict):
            assert "subject_id" not in o, path
            for k, v in o.items():
                walk(v, f"{path}.{k}")
        elif isinstance(o, list):
            assert len(o) <= 64, f"{path}: array of length {len(o)}"
            for i, v in enumerate(o):
                walk(v, f"{path}[{i}]")
    walk(analysis)


def test_analyze_us_bounds_without_keys_exits_2(prepared, tmp_path):
    bad = tmp_path / "us_bad.json"
    bad.write_text(json.dumps({"data_source": "real", "coverage": {"recorded": {}}}))
    r = run(ANALYZE, "--prepared", str(prepared), "--us-bounds", str(bad), "--fixture",
            "--out", str(tmp_path / "a.json"))
    assert r.returncode == 2 and "auroc_lo" in r.stderr
    assert not (tmp_path / "a.json").exists()
    r2 = run(ANALYZE, "--prepared", str(prepared), "--us-bounds", str(tmp_path / "absent.json"),
             "--fixture", "--out", str(tmp_path / "b.json"))
    assert r2.returncode == 2


def test_analyze_provenance_mismatch_exits_3(prepared, us_bounds, tmp_path):
    r = run(ANALYZE, "--prepared", str(prepared), "--us-bounds", str(us_bounds),
            "--out", str(tmp_path / "a.json"))               # no --fixture on a synthetic sidecar
    assert r.returncode == 3 and "PROVENANCE MISMATCH" in r.stderr
    assert not (tmp_path / "a.json").exists()


def test_analyze_null_comparison_without_us_values(prepared, tmp_path):
    us = tmp_path / "us.json"
    us.write_text(json.dumps({"data_source": "synthetic", "gamma": 1.5, "auroc_lo": 0.6, "auroc_hi": 0.7}))
    out = tmp_path / "a.json"
    r = run(ANALYZE, "--prepared", str(prepared), "--us-bounds", str(us), "--fixture",
            "--nuisance-model", "logistic", "--no-calibrate", "--n-boot", "5", "--seeds", "5",
            "--out", str(out))
    assert r.returncode == 0, r.stderr + r.stdout
    with open(out) as f:
        d = json.load(f)
    assert d["gamma_comparison"]["gamma_min_vs_us"] is None
    assert d["gamma_comparison"]["odds_ratio_vs_us"] is None
    assert d["containment"]["min_gamma_containing"]["method"] == "single_endpoint"


# ------------------------------------------------------ (d) placeholder
def test_write_pending_to_tmp(tmp_path):
    before = results_snapshot()
    repo_pending = os.path.join(RESULTS, "korea_cohort_pending.json")
    existed = os.path.exists(repo_pending)
    out = tmp_path / "korea_cohort_pending.json"
    r = run(ANALYZE, "--write-pending", "--out", str(out))
    assert r.returncode == 0, r.stderr
    with open(out) as f:
        d = json.load(f)
    assert d["data_source"] == "pending"
    assert d["status"] == "pending IRB"
    assert d["containment"] is None and d["gamma_comparison"] is None and d["n_seeds"] is None
    assert os.path.exists(repo_pending) == existed
    assert results_snapshot() == before, "tests must not write into results/"
