"""Tests for dcl.data.mimic_ecg_echo.{io,linkage} against the tiny pytest fixture.

The fixture (tests/fixtures/mimic_ecg_echo) is generated by
scripts/make_mimic_fixture.py; hand-checkable cases are documented there.
No number derived from the fixture may be reported anywhere.
"""
from __future__ import annotations

import filecmp
import gzip
import importlib.util
import os
import sys

import numpy as np
import pandas as pd
import pytest

from dcl.data.mimic_ecg_echo import (DataRoot, EXPECTED_COLUMNS, TABLES,
                                     attach_decision_maker, compute_echo_coverage_window,
                                     dedup_ecgs, link_ecg_to_echo, restrict_to_coverage)

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURE = os.path.join(REPO, "tests", "fixtures", "mimic_ecg_echo")
PKG = os.path.join(REPO, "dcl", "data", "mimic_ecg_echo")
FIXTURE_TABLES = ("record_list", "echo_study_list", "echo_record_list",
                  "patients", "admissions", "transfers")
S = 90_000_000


@pytest.fixture(scope="module")
def root() -> DataRoot:
    return DataRoot(FIXTURE)


@pytest.fixture(scope="module")
def tables(root):
    return {name: root.load_table(name) for name in FIXTURE_TABLES}


# ------------------------------------------------------------------- io
def test_fixture_provenance_is_fixture(root, tables):
    assert root.source == "fixture"
    for name, (df, prov) in tables.items():
        assert prov["source"] == "fixture"
        assert prov["table"] == name
        assert os.path.isabs(prov["path"]) and os.path.isfile(prov["path"])
        assert prov["n_rows"] == len(df) and 0 < prov["n_rows"] <= 50
        assert len(prov["sha256"]) == 64 and prov["sha256_bytes"] == 1 << 20
        assert prov["columns"] == list(df.columns)
        assert set(EXPECTED_COLUMNS[name]) <= set(df.columns)
        assert (df["subject_id"] >= S).all()
    assert not root.all_real()


def test_datetimes_parsed(tables):
    assert pd.api.types.is_datetime64_any_dtype(tables["record_list"][0]["ecg_time"])
    assert pd.api.types.is_datetime64_any_dtype(tables["echo_study_list"][0]["study_datetime"])
    tr = tables["transfers"][0]
    assert pd.api.types.is_datetime64_any_dtype(tr["intime"])
    assert tr["outtime"].isna().any()  # open-ended / discharge rows


def test_missing_file_exits_2(tmp_path, capsys):
    dr = DataRoot(str(tmp_path), source="real")
    with pytest.raises(SystemExit) as e:
        dr.load_table("record_list")
    assert e.value.code == 2
    err = capsys.readouterr().err
    expected_path = os.path.join(str(tmp_path), TABLES["record_list"][1])
    assert expected_path in err
    assert "physionet.org" in err and "mimic-iv-ecg" in err
    assert "simulator" in err.lower()


def test_require_direct_exits_2(tmp_path, capsys):
    dr = DataRoot(str(tmp_path), source="real")
    with pytest.raises(SystemExit) as e:
        dr.require(str(tmp_path / "nope.csv"), "mimic-iv-echo")
    assert e.value.code == 2
    assert "nope.csv" in capsys.readouterr().err


def test_schema_mismatch_exits_2(tmp_path, capsys):
    (tmp_path / "record_list.csv").write_text(
        "subject_id,study_id,path,ecg_time\n90000001,1,x,2018-01-01 00:00:00\n")
    dr = DataRoot(str(tmp_path), source="real")
    with pytest.raises(SystemExit) as e:
        dr.load_table("record_list")
    assert e.value.code == 2
    err = capsys.readouterr().err
    assert "SCHEMA MISMATCH" in err
    assert "file_name" in err and "path" in err          # expected + actual headers
    assert "mimic-iv-ecg v1.0" in err                      # dataset version
    # gz tables are checked the same way
    (tmp_path / "hosp").mkdir()
    with gzip.open(tmp_path / "hosp" / "patients.csv.gz", "wt") as f:
        f.write("subject_id,sex\n90000001,F\n")
    with pytest.raises(SystemExit) as e:
        dr.load_table("patients")
    assert e.value.code == 2
    assert "mimic-iv v3.1" in capsys.readouterr().err


def test_extra_columns_tolerated_and_usecols(tmp_path):
    (tmp_path / "echo-study-list.csv").write_text(
        "subject_id,study_id,study_datetime,extra\n90000001,1,2018-01-01 00:00:00,q\n")
    df, prov = DataRoot(str(tmp_path), source="real").load_table(
        "echo_study_list", usecols=["subject_id", "study_datetime"])
    assert list(df.columns) == ["subject_id", "study_datetime"]
    assert prov["source"] == "real" and prov["header"][-1] == "extra"


def test_fixture_dir_cannot_be_labelled_real():
    with pytest.raises(ValueError):
        DataRoot(FIXTURE, source="real")
    with pytest.raises(ValueError):
        DataRoot(FIXTURE, source="synthetic")
    with pytest.raises(KeyError):
        DataRoot(FIXTURE).path("no_such_table")


def test_no_simulator_import_in_package():
    """CLAUDE.md rule 1 / spec: make_mimic_sim is never imported in this package."""
    for fn in os.listdir(PKG):
        if not fn.endswith(".py"):
            continue
        with open(os.path.join(PKG, fn)) as f:
            for line in f:
                code = line.split("#", 1)[0].strip()
                if code.startswith(("from ", "import ")):
                    assert "make_mimic_sim" not in code, (fn, code)
                    assert "..mimic" not in code and "dcl.data.mimic " not in code, (fn, code)
                assert "make_mimic_sim(" not in code, (fn, code)
    import dcl.data.mimic_ecg_echo as pkg
    assert not hasattr(pkg, "make_mimic_sim")


# ------------------------------------------------------------- linkage
@pytest.fixture(scope="module")
def linked(tables):
    return link_ecg_to_echo(tables["record_list"][0], tables["echo_study_list"][0])


def _row(df, study_id):
    r = df.loc[df["study_id"] == study_id]
    assert len(r) == 1
    return r.iloc[0]

def test_link_window_boundary(linked, tables):
    rec = tables["record_list"][0]
    assert len(linked) == len(rec) and (linked["study_id"].to_numpy() == rec["study_id"].to_numpy()).all()
    assert set(linked["T"].unique()) <= {0, 1}
    r = _row(linked, 40_000_001)          # +365 d -> in
    assert r["T"] == 1 and r["days_to_nearest_echo"] == 365.0 and r["nearest_echo_study_id"] == 50_000_001
    r = _row(linked, 40_000_002)          # +366 d -> out
    assert r["T"] == 0 and r["days_to_nearest_echo"] == 366.0 and r["nearest_echo_study_id"] == 50_000_002
    r = _row(linked, 40_000_003)          # -365 d -> in
    assert r["T"] == 1 and r["days_to_nearest_echo"] == -365.0
    r = _row(linked, 40_000_005)          # subject without echo
    assert r["T"] == 0 and np.isnan(r["days_to_nearest_echo"]) and pd.isna(r["nearest_echo_study_id"])
    # window is a parameter
    l2 = link_ecg_to_echo(rec, tables["echo_study_list"][0], window_days=364)
    assert _row(l2, 40_000_001)["T"] == 0
    l3 = link_ecg_to_echo(rec, tables["echo_study_list"][0], window_days=366)
    assert _row(l3, 40_000_002)["T"] == 1


def test_link_nearest_and_ties():
    rec = pd.DataFrame({"subject_id": [S + 1], "study_id": [1],
                        "ecg_time": pd.to_datetime(["2018-06-01"])})
    echo = pd.DataFrame({"subject_id": [S + 1] * 3, "study_id": [30, 10, 20],
                         "study_datetime": pd.to_datetime(["2018-05-22", "2018-06-11", "2019-09-01"])})
    r = link_ecg_to_echo(rec, echo).iloc[0]
    assert r["T"] == 1 and abs(r["days_to_nearest_echo"]) == 10 and r["nearest_echo_study_id"] == 10
    with pytest.raises(ValueError):
        link_ecg_to_echo(pd.concat([rec, rec]), echo)


def test_coverage_window_and_restriction(tables):
    rec, echo = tables["record_list"][0], tables["echo_study_list"][0]
    lo, hi = compute_echo_coverage_window(echo)
    assert lo == pd.Timestamp("2017-03-01") and hi == pd.Timestamp("2019-10-31")
    kept, prov = restrict_to_coverage(rec, (lo, hi), pad_days=365)
    assert prov["n_before"] == 36 and prov["n_after"] == 33 and prov["n_dropped"] == 3
    assert prov["echo_coverage_window"] == [lo.isoformat(), hi.isoformat()]
    dropped = set(rec["study_id"]) - set(kept["study_id"])
    assert dropped == {40_000_004, 40_000_012, 40_000_013}
    assert 40_000_014 in set(kept["study_id"])          # == echo_min - 365 d, inclusive
    assert (kept["ecg_time"] >= lo - pd.Timedelta(days=365)).all()
    assert (kept["ecg_time"] <= hi + pd.Timedelta(days=365)).all()
    kept0, prov0 = restrict_to_coverage(rec, (lo, hi), pad_days=0)
    assert prov0["n_after"] == 36 - 6  # also drops 40000014, 40000015 (2017-02-10), 40000016 (2019-11-20)
    assert len(rec) == 36  # input not mutated


def test_dedup_rule(tables):
    rec = tables["record_list"][0]
    out, prov = dedup_ecgs(rec, min_gap_days=30)
    s5 = out.loc[out["subject_id"] == S + 5, "study_id"].tolist()
    assert s5 == [40_000_006, 40_000_009, 40_000_011]    # days 0, 30, 61 kept; 10, 29, 45 dropped
    assert prov["n_before"] == 36 and prov["n_after"] == 36 - 3
    assert prov["min_gap_days"] == 30.0 and "keep the first" in prov["rule"]
    assert out.index.is_monotonic_increasing                # input order preserved
    # every kept pair of one subject is >= 30 d apart
    for _, g in out.groupby("subject_id"):
        t = g["ecg_time"].sort_values().to_numpy()
        if len(t) > 1:
            assert (np.diff(t) >= np.timedelta64(30, "D")).all()
    # greedy anchoring on the last kept ECG, ties broken by study_id
    df = pd.DataFrame({"subject_id": [S + 9] * 4, "study_id": [4, 3, 2, 1],
                       "ecg_time": pd.to_datetime(["2018-01-01", "2018-02-10", "2018-03-07", "2018-01-01"])})
    o, _ = dedup_ecgs(df, 30)
    assert o["study_id"].tolist() == [3, 1]                # day 0 (id 1), day 40 kept, day 65 (25 d later) dropped


def test_decision_maker_attachment_and_fallback(tables, linked):
    tr, adm = tables["transfers"][0], tables["admissions"][0]
    services = pd.DataFrame({
        "subject_id": [S + 2, S + 2, S + 4],
        "hadm_id": [20_000_002, 20_000_002, 20_000_099],
        "transfertime": pd.to_datetime(["2017-12-28 10:00:00", "2017-12-30 09:00:00",
                                        "2018-09-10 00:00:00"]),
        "prev_service": [None, "MED", None],
        "curr_service": ["MED", "CMED", "SURG"],
    })
    # careunit only
    z = attach_decision_maker(linked, tr)
    assert list(z["study_id"]) == list(linked["study_id"]) and "T" in z
    assert _row(z, 40_000_001)["Z"] == "Medical Intensive Care Unit (MICU)"
    assert _row(z, 40_000_001)["Z_source"] == "careunit"
    assert _row(z, 40_000_003)["Z"] == "Cardiac Surgery"     # open-ended outtime
    assert _row(z, 40_000_002)["Z"] == "unknown"             # transfer ended before ECG
    assert _row(z, 40_000_005)["Z"] == "unknown"
    # + admissions: admission_location fallback
    z = attach_decision_maker(linked, tr, admissions=adm)
    assert _row(z, 40_000_002)["Z"] == "EMERGENCY ROOM"
    assert _row(z, 40_000_002)["Z_source"] == "admission_location"
    assert _row(z, 40_000_001)["Z_source"] == "careunit"     # careunit still wins
    assert _row(z, 40_000_005)["Z"] == "unknown"
    # + services: curr_service beats admission_location, careunit still first
    z = attach_decision_maker(linked, tr, services=services, admissions=adm)
    assert _row(z, 40_000_002)["Z"] == "CMED" and _row(z, 40_000_002)["Z_source"] == "curr_service"
    assert _row(z, 40_000_001)["Z_source"] == "careunit"
    # service of an admission without a spanning admission row: dischtime unknown -> accepted
    assert _row(z, 40_000_005)["Z"] == "SURG"
    # ... but rejected when admissions say that admission ended before the ECG
    adm2 = pd.concat([adm, pd.DataFrame({
        "subject_id": [S + 4], "hadm_id": [20_000_099],
        "admittime": pd.to_datetime(["2018-09-10"]), "dischtime": pd.to_datetime(["2018-09-12"]),
        "deathtime": [pd.NaT], "admission_type": ["URGENT"],
        "admission_location": ["CLINIC REFERRAL"], "discharge_location": ["HOME"]})],
        ignore_index=True)
    z = attach_decision_maker(linked, tr, services=services, admissions=adm2)
    assert _row(z, 40_000_005)["Z"] == "unknown"
    assert set(z["Z_source"]) <= {"careunit", "curr_service", "admission_location", "unknown"}
    assert z["Z"].notna().all()
    assert "Z" not in linked.columns                          # input not mutated


# ------------------------------------------------------------- fixture
def _load_generator():
    spec = importlib.util.spec_from_file_location(
        "make_mimic_fixture", os.path.join(REPO, "scripts", "make_mimic_fixture.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_fixture_generator_is_deterministic_and_checked_in(tmp_path):
    gen = _load_generator()
    tables_ = gen.build_tables()
    for name, df in tables_.items():
        assert len(df) <= 50 and (df["subject_id"] >= S).all(), name
    gen.write_tables(tables_, str(tmp_path))
    for name in tables_:
        assert filecmp.cmp(os.path.join(FIXTURE, name), os.path.join(str(tmp_path), name),
                           shallow=False), f"{name}: regenerate with scripts/make_mimic_fixture.py"


def test_fixture_generator_refuses_results_dir(tmp_path, monkeypatch):
    gen = _load_generator()
    monkeypatch.setattr(sys, "argv", ["make_mimic_fixture.py", "--out",
                                      str(tmp_path / "results" / "fx")])
    with pytest.raises(SystemExit):
        gen.main()
    assert not (tmp_path / "results").exists()
    assert not os.path.exists(os.path.join(REPO, "results", "mimic_ecg_echo"))
