"""Unit tests for dcl.data.mimic_ecg_echo.{outcomes,notes_regex,covariates}.

In-memory frames plus the pytest fixture (tests/fixtures/mimic_ecg_echo,
generated by scripts/make_mimic_fixture.py).  No number derived from the
fixture may be reported anywhere.
"""
from __future__ import annotations

import os

import numpy as np
import pandas as pd
import pytest

from dcl.data.mimic_ecg_echo import DataRoot, link_ecg_to_echo
from dcl.data.mimic_ecg_echo import covariates as cov
from dcl.data.mimic_ecg_echo import outcomes as outc
from dcl.data.mimic_ecg_echo.notes_regex import extract_note

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURE = os.path.join(REPO, "tests", "fixtures", "mimic_ecg_echo")
S = 90_000_000
COMPONENTS = [c["name"] for c in outc.ECHONEXT_SHD_COMPONENTS]


# ------------------------------------------------------ (a) structured echo
def test_compute_structured_shd_components_and_composite():
    meas = pd.DataFrame({
        "study_id": [1, 2, 3, 4, 5, 6, 7, 8],
        "lvef": [60, 35, 60, 60, np.nan, 0.55, 58, 62],
        "ivsd": [1.0, 1.0, 14.0, 1.0, np.nan, 1.0, 1.0, 1.0],       # row 3: mm -> 1.4 cm
        "lvpwd": [0.9, 0.9, 0.9, 0.9, np.nan, 0.9, 0.9, 0.9],
        "aortic_stenosis": ["mild", "none", "none", "severe", None, "trace", "none", "none"],
        "mr_grade": ["none", "none", "none", "none", None, "none", "moderate to severe", "mild-to-moderate"],
        "tr_vmax": [2.5, 2.5, 2.5, 2.5, np.nan, 2.5, 2.5, 3.4],
        "rvsp": [30, 30, 30, 30, np.nan, 30, 30, 50],
    })
    out = outc.compute_structured_shd(meas)
    assert list(out.columns) == COMPONENTS + ["shd_echo_struct", "n_components_evaluated"]
    assert len(out) == len(meas)
    shd = out["shd_echo_struct"].tolist()
    assert shd[0] == 0.0                                    # everything below threshold
    assert shd[1] == 1.0 and out.loc[1, "lvef_lte_45"] == 1.0
    assert shd[2] == 1.0 and out.loc[2, "lvwt_gte_13"] == 1.0   # 14 mm -> 1.4 cm >= 1.3
    assert shd[3] == 1.0 and out.loc[3, "aortic_stenosis_moderate_severe"] == 1.0
    assert np.isnan(shd[4]) and out.loc[4, "n_components_evaluated"] == 0
    assert shd[5] == 0.0 and out.loc[5, "lvef_lte_45"] == 0.0   # fraction 0.55 -> 55 %
    assert shd[6] == 1.0 and out.loc[6, "mitral_regurgitation_moderate_severe"] == 1.0
    assert out.loc[7, "mitral_regurgitation_moderate_severe"] == 0.0   # mild-to-moderate < moderate
    assert out.loc[7, "tr_max_gte_32"] == 1.0 and out.loc[7, "pasp_gte_45"] == 1.0 and shd[7] == 1.0
    # components never measured stay NaN, evaluated ones are counted
    assert out["pericardial_effusion_moderate_large"].isna().all()
    assert out.loc[0, "n_components_evaluated"] == 6
    # explicit column map overrides alias matching
    out2 = outc.compute_structured_shd(meas.rename(columns={"lvef": "weird"}), column_map={"lvef": "weird"})
    assert out2["lvef_lte_45"].tolist()[:2] == [0.0, 1.0]


def test_detect_structured_measurements_absent_on_fixture():
    det = outc.detect_structured_echo_measurements(FIXTURE, echo_subdir=".")
    assert det["available"] is False and det["path"] is None
    assert "unavailable" in det["provenance_note"]


# ------------------------------------------------------------- (b) notes
@pytest.mark.parametrize("text, lvef, shd, valve_c", [
    ("TTE showed LVEF 30% with global hypokinesis.", 30.0, 1, None),
    ("Echo: EF 55-60%, no evidence of moderate or severe AS or MR.", 57.5, 0, False),   # negated
    ("Severe aortic stenosis was noted on echocardiogram; EF preserved.", None, 1, True),
    ("Echo: no LVH. Normal LVEF. Mild MR.", None, 0, False),                            # negated LVH
    ("Patient has a history of multiple sclerosis (MS); admitted for cellulitis.", None, None, None),
    ("IVSd 1.5 cm, LVPWd 1.4 cm, EF 60%.", 60.0, 1, None),
    ("Echo without significant mitral regurgitation, EF 65%.", 65.0, 0, False),          # negated
])
def test_regex_extraction_sentences(text, lvef, shd, valve_c):
    r = extract_note(text)
    assert r["lvef"] == lvef
    assert r["shd_composite"] == shd
    assert r["components"]["valve_moderate_or_severe"] is valve_c
    assert r["extractor"] == "regex"


def test_regex_extraction_details():
    r = extract_note("Echo: EF 55-60%, no evidence of moderate or severe AS or MR.")
    assert r["components"]["lvef_le_45"] is False
    assert [(v["valve"], v["severity"], v["negated"]) for v in r["valve_lesions"]] == [("AS", "none", True)]
    r = extract_note("Echo without significant mitral regurgitation, EF 65%.")
    assert r["valve_lesions"][0]["valve"] == "MR" and r["valve_lesions"][0]["negated"] is True
    r = extract_note("Echo: no LVH. Normal LVEF. Mild MR.")
    assert r["lvh_negated"] is True and r["components"]["wall_ge_1p3"] is False
    assert r["lvef_qualitative"] == "normal"
    r = extract_note("IVSd 1.5 cm, LVPWd 1.4 cm, EF 60%.")
    assert r["wall_thickness_cm"] == 1.5 and r["septal_cm"] == 1.5 and r["posterior_cm"] == 1.4
    r = extract_note("Echocardiogram showed moderate concentric LVH and moderate to severe mitral "
                     "regurgitation; LVEF 55%.")
    assert r["lvh_qualitative"] == "moderate" and r["components"]["wall_ge_1p3"] is True
    assert r["valve_lesions"][0]["severity"] == "moderate_severe" and r["shd_composite"] == 1
    assert 0.0 < r["confidence"] <= 1.0
    e = extract_note("")
    assert e["shd_composite"] is None and e["n_fields_found"] == 0 and e["confidence"] == 0.0


# ---------------------------------------------------------------- (c) ICD
def _records():
    return pd.DataFrame({
        "subject_id": [S + 1, S + 2, S + 3, S + 4],
        "study_id": [1, 2, 3, 4],
        "ecg_time": pd.to_datetime(["2018-01-02", "2018-02-02", "2018-03-02", "2018-04-02"]),
    })


def test_label_from_icd_sources_and_priority():
    rec = _records()
    ecg_icd = pd.DataFrame({"study_id": [1, 2], "all_diag_all": ["['I5023', 'E119']", "['E119', 'J189']"]})
    adm = pd.DataFrame({
        "subject_id": [S + 3, S + 4], "hadm_id": [10, 11],
        "admittime": pd.to_datetime(["2018-03-01", "2018-04-01"]),
        "dischtime": pd.to_datetime(["2018-03-05", "2018-04-05"]),
    })
    dx = pd.DataFrame({"subject_id": [S + 3, S + 3, S + 4], "hadm_id": [10, 10, 11],
                       "icd_code": ["I35.0", "E119", "4280"], "icd_version": [10, 10, 9]})
    out = outc.label_from_icd(rec, dx, ecg_icd, adm)
    assert out["Y_icd"].tolist()[:3] == [1.0, 0.0, 1.0] and np.isnan(out["Y_icd"].iloc[3])
    assert out["icd_source"].tolist() == ["mimic_ecg_icd", "mimic_ecg_icd", "hosp_admission",
                                          "hosp_admission_icd9_only"]
    assert out["icd_matched"].tolist()[:3] == ["I5023", "", "I350"]      # dots removed
    assert out["icd_hadm_id"].iloc[2] == 10
    with pytest.raises(ValueError):
        outc.label_from_icd(rec, None, None, None)
    # hosp route alone, without the ECG-ICD table
    out2 = outc.label_from_icd(rec, dx, None, adm)
    assert np.isnan(out2["Y_icd"].iloc[0]) and out2["icd_source"].iloc[0] == "none"
    assert out2["Y_icd"].iloc[2] == 1.0


def test_icd_circularity_diagnostic():
    y = np.array([1, 0, 1, np.nan, 0, 1, 0, 0])
    T = np.array([1, 1, 1, 1, 0, 0, 0, 0])
    linked = np.array([True, True, True, True, False, True, False, False])
    d = outc.icd_circularity_diagnostic(y, T, linked)
    assert d["n"] == 8 and d["n_assessable"] == 7
    t1, t0 = d["icd_rate_by_T"]["T1"], d["icd_rate_by_T"]["T0"]
    assert t1["n"] == 3 and t1["n_pos"] == 2 and t1["rate"] == pytest.approx(2 / 3)
    assert t0["n"] == 4 and t0["n_pos"] == 1 and t0["rate"] == pytest.approx(0.25)
    assert d["icd_rate_by_T"]["risk_ratio"] == pytest.approx((2 / 3) / 0.25)
    assert d["icd_rate_by_T"]["risk_difference"] == pytest.approx(2 / 3 - 0.25)
    lo, hi = t1["ci95"]
    assert 0.0 <= lo < t1["rate"] < hi <= 1.0                      # Wilson interval
    e = d["icd_rate_by_echo_linked"]
    assert e["linked"]["n"] == 4 and e["not_linked"]["n"] == 3
    assert outc.icd_circularity_diagnostic(y, T)["icd_rate_by_echo_linked"] is None
    with pytest.raises(ValueError):
        outc.icd_circularity_diagnostic(y, T[:-1])


# ------------------------------------------------------------ covariates
def test_assert_no_forbidden():
    for bad in ("Y_note", "T", "Z", "lvef_mean", "nearest_echo_days", "careunit", "dischtime",
                "study_id", "shd", "note_confidence", "icd_matched", "echo_time", "days_to_nearest_echo"):
        with pytest.raises(cov.ForbiddenFeatureError):
            cov.assert_no_forbidden(["age_at_ecg", bad])
        assert cov.is_forbidden(bad) is not None
    good = ["age_at_ecg", "sex_male", "lab_troponin", "lab_troponin_missing", "ecg_rr", "ecg_qtc",
            "setting_ed", "ecg_emb_001", "tabular_x"]
    cov.assert_no_forbidden(good)                                   # no raise
    assert all(cov.is_forbidden(g) is None for g in good)
    assert issubclass(cov.ForbiddenFeatureError, AssertionError)


def test_assemble_X_shapes_and_imputation():
    idx = pd.RangeIndex(6)
    a = pd.DataFrame({"age_at_ecg": [50, 60, np.nan, 70, 80, 90], "sex_male": [1, 0, 1, np.nan, 0, 1]}, index=idx)
    b = pd.DataFrame({"lab_bnp": [np.nan] * 6, "ecg_rr": [800, 900, 1000, np.nan, 700, 750]}, index=idx)
    train = np.array([True, True, True, False, False, False])
    with pytest.warns(UserWarning):                                  # lab_bnp all-NaN on train -> 0
        X, names, imp = cov.assemble_X({"demo": a, "rest": b}, train)
    assert X.shape == (6, 4) and names == ["age_at_ecg", "sex_male", "lab_bnp", "ecg_rr"]
    assert not np.isnan(X).any()
    assert X[2, 0] == 55.0                    # median of the TRAIN rows (50, 60), not of all rows
    assert X[3, 3] == 900.0                   # train median of ecg_rr (800, 900, 1000)
    assert (X[:, 2] == 0.0).all()
    X2, _, _ = cov.assemble_X({"demo": a, "rest": b}, train, imputer=imp)
    assert np.array_equal(X, X2)
    with pytest.raises(cov.ForbiddenFeatureError):
        cov.assemble_X({"demo": a, "bad": pd.DataFrame({"Y_note": np.zeros(6)}, index=idx)}, train)
    with pytest.raises(ValueError):
        cov.assemble_X({"demo": a, "b": b.iloc[:5]}, train)
    with pytest.raises(ValueError):
        cov.assemble_X({"demo": a}, np.zeros(6, dtype=bool))
    with pytest.raises(TypeError):
        cov.assemble_X({"demo": a.assign(sex_male=["M"] * 6)}, train)


@pytest.fixture(scope="module")
def fx():
    root = DataRoot(FIXTURE)
    names = ("record_list", "echo_study_list", "patients", "admissions", "labevents", "d_labitems",
             "edstays", "machine_measurements", "discharge")
    t = {n: root.load_table(n)[0] for n in names}
    t["records"] = link_ecg_to_echo(t["record_list"], t["echo_study_list"])
    return t


def test_covariate_blocks_on_fixture(fx):
    rec = fx["records"]
    blocks = cov.covariate_blocks(rec, patients=fx["patients"], labevents=fx["labevents"],
                                  d_labitems=fx["d_labitems"], edstays=fx["edstays"],
                                  admissions=fx["admissions"], machine_measurements=fx["machine_measurements"],
                                  verbose=False)
    assert set(blocks) == {"demographics", "labs", "setting", "ecg_tabular"}
    n = len(rec)
    assert blocks["demographics"].shape == (n, 2) and blocks["labs"].shape == (n, 8)
    assert blocks["setting"].shape == (n, 3) and blocks["ecg_tabular"].shape == (n, 8)
    for b in blocks.values():
        assert b.index.equals(rec.index)
        cov.assert_no_forbidden(b.columns)
    assert (blocks["setting"].sum(axis=1) == 1.0).all()
    row = rec.index[rec["study_id"] == 40_000_025][0]
    assert blocks["setting"].loc[row, "setting_ed"] == 1.0            # ED stay contains the ECG
    row1 = rec.index[rec["study_id"] == 40_000_001][0]
    assert blocks["setting"].loc[row1, "setting_inpatient"] == 1.0
    # labs: subject 90000001 has haemoglobin 13.1 after the ECG, 12.4 at 30 h, 11.8 at 5 h before
    assert blocks["labs"].loc[row1, "lab_hemoglobin"] == 11.8
    assert blocks["labs"].loc[row1, "lab_hemoglobin_missing"] == 0.0
    assert blocks["labs"]["lab_troponin_missing"].sum() == n - 12
    # demographics: anchor_age + (year(ecg) - anchor_year); patients row for S1 is F, 39, 2018
    assert blocks["demographics"].loc[row1, "age_at_ecg"] == 39.0 and blocks["demographics"].loc[row1, "sex_male"] == 0.0
    # machine measurements: sentinel 29999 rows become NaN for PR and P axis only
    et = blocks["ecg_tabular"]
    sentinel = fx["machine_measurements"]["p_onset"] == 29999.0
    assert sentinel.sum() == 4 and et.loc[sentinel.to_numpy(), "ecg_pr"].isna().all()
    assert et.loc[sentinel.to_numpy(), "ecg_p_axis"].isna().all()
    assert et.loc[~sentinel.to_numpy(), ["ecg_rr", "ecg_pr", "ecg_qrs", "ecg_qt", "ecg_qtc"]].notna().all().all()
    X, names, _ = cov.assemble_X(blocks, np.ones(n, dtype=bool))
    assert X.shape == (n, 21) and len(names) == 21


def test_label_from_notes_on_fixture(fx):
    rec = fx["records"].copy()
    et = fx["echo_study_list"].set_index("study_id")["study_datetime"]
    rec["echo_time"] = pd.to_datetime(et.reindex(rec["nearest_echo_study_id"].astype("float")).to_numpy())
    rec.loc[rec["T"] != 1, "echo_time"] = pd.NaT
    out = outc.label_from_notes(rec, fx["discharge"], fx["admissions"])
    assert out.index.equals(rec.index) and set(out["Y_note"].dropna().unique()) <= {0.0, 1.0}
    r1 = out.loc[rec["study_id"] == 40_000_001].iloc[0]           # hadm 20000001 -> template 0 (LVEF 30 %)
    assert r1["Y_note"] == 1.0 and r1["note_lvef"] == 30.0 and r1["note_n_notes"] == 1
    r2 = out.loc[rec["study_id"] == 40_000_002].iloc[0]           # template 1: EF 55-60 %, negated valves
    assert r2["Y_note"] == 0.0 and r2["note_lvef"] == 57.5 and r2["note_wall_cm"] == 0.9
    s11 = out.loc[rec["subject_id"] == S + 11]                    # template 5: no cardiac work-up
    assert s11["Y_note"].isna().all() and (s11["note_n_notes"] == 1).all()
    s5 = out.loc[rec["subject_id"] == S + 5]                      # admission contains the echo
    assert (s5["note_link"] == "echo_admission").all()
    s4 = out.loc[rec["subject_id"] == S + 4]                      # no admission, no note
    assert s4["Y_note"].isna().all() and (s4["note_n_notes"] == 0).all() and (s4["note_link"] == "none").all()
